export const CARD_CATEGORIES = {
  ALL: 'ALL',
  ATTACK: 'ATTACK',
  DEFENSE: 'DEFENSE',
  SPECIAL: 'SPECIAL',
  MOVEMENT: 'MOVEMENT',
  ECONOMIC: 'ECONOMIC',
}

export const CARD_CATEGORIES_LABEL = {
  [CARD_CATEGORIES.ALL]: '全部',
  [CARD_CATEGORIES.ATTACK]: '攻擊',
  [CARD_CATEGORIES.DEFENSE]: '防禦',
  [CARD_CATEGORIES.SPECIAL]: '特殊',
  [CARD_CATEGORIES.MOVEMENT]: '移動',
  [CARD_CATEGORIES.ECONOMIC]: '金錢',
}

export const CARD_CATEGORIES_COLOR = {
  [CARD_CATEGORIES.ATTACK]: 'red',
  [CARD_CATEGORIES.DEFENSE]: 'blue',
  [CARD_CATEGORIES.SPECIAL]: 'purple',
  [CARD_CATEGORIES.MOVEMENT]: 'green',
  [CARD_CATEGORIES.ECONOMIC]: 'yellow',
}
